### PR TITLE
automation and improvements

### PR DESCRIPTION
**Pull request by nicolaasuni**
- merging bpowers changes to add constructor + accessor for underlying bit array;
- add Makefile to automate repetitive tasks;
- fix "golint" and "vet" errors;
- add Travis-CI configuration for automatic QA checks;
- updated README (you may want to remove the travis-ci and coveralls badges or update the links with your account.

### CODE REVIEW

**Comment by lemire** [comment]
@nicolaasuni 

> removing ASM files as they were not showing any performance improvement 

I don't disagree with the removal of the ASM files, but I disagree with the claim that there is no performance gain to having them. It would be helpful to share your own numbers and testing protocol. I would recommend...

1. Latest Intel processor (Skylake or better)
2. Recent go version (1.5 or better)

On my Skylake box...

Before
```
$ go test -bench=BenchmarkCount
BenchmarkCount-4	  500000	      2315 ns/op
```

After 

```
$  go test -bench=BenchmarkCount
BenchmarkCount-4	  500000	      3245 ns/op
```


But, again, I don't disagree with the removal of the ASM files... but if the argument is based on performance, it needs to be backed by actual benchmarks I would think.

A more serious concern, in my mind, is that Google App engine wants nothing to do with assembly or cgo.

**Comment by lemire** [comment]
Throughout the PR, the project is called ```cognitivelogic/bitset```. Given that this is a PR to ```willf/bitset```, it seems like it can be confusing.

**Comment by willf** [comment]
Thanks for the comments. I hope to review the request tonight.

**Comment by nicolaasuni** [comment]
@lemire Sorry, my fault in executing the benchmark tests. Effectively the ASM version is faster. However I had issues with golint indicating several errors on the ASM file. I found that the pure-GO version is more portable and easy to maintain.

As indicated in the PR request, feel free to replace the cognitivelogic/bitset with willf/bitset. This change is necessary on my side to get the Travis-CI and Coveralls badges on my fork.

**Comment by lemire** [comment]
@nicolaasuni 

Can you give examples of portability and maintenance issues caused by the assembly?


@salviati Submitted the ASM files in this PR: https://github.com/willf/bitset/pull/19

He documented a 60% reduction in running time. 


This gain from assembly fell significantly with the PR that I myself introduced...

https://github.com/willf/bitset/pull/21

At the time, I could have argued for the removal of the assembly files... but I was happy just improving the pure Go performance... and I could not be sure that the assembly wasn't useful on some configurations.

Retesting today, with a difference version of Go, I find that gains from assembly are ~18% on haswell and ~30% on skylake. 

No matter how you put it, the gains from @salviati's assembly are much less than they were when he introduced it. The pure Go code has gotten better. However, the gains are still there and 30% is nothing to sneeze at. Note that I'd like independent confirmation of my benchmark results.

Would I recommend using assembly to speed things up by 30%? Probably not... but we have the assembly now, it costs nothing. 


I'd really like to understand @nicolaasuni 's argument about maintenance and portability. As far as I can tell, we can just ignore the assembly for all practical purposes. It is an unchanging resource that is well tested and, as far as we know, bug free.

**Comment by nicolaasuni** [comment]
When executing "go vet" on the code with the ASM file I got:
```
$ go vet ./...
popcnt_amd64.s:1: +build comment must appear before package clause and be followed by a blank line
popcnt_amd64.s:2: [amd64] hasAsm: wrong argument size 0; expected $...-1
popcnt_amd64.s:16: [amd64] popcntSliceAsm: invalid offset s+8(FP); expected s+0(FP), s_base+0(FP), s_len+8(FP), or s_cap+16(FP)
popcnt_amd64.s:31: [amd64] popcntMaskSliceAsm: invalid offset s+8(FP); expected s+0(FP), s_base+0(FP), s_len+8(FP), or s_cap+16(FP)
popcnt_amd64.s:51: [amd64] popcntAndSliceAsm: invalid offset s+8(FP); expected s+0(FP), s_base+0(FP), s_len+8(FP), or s_cap+16(FP)
popcnt_amd64.s:70: [amd64] popcntOrSliceAsm: invalid offset s+8(FP); expected s+0(FP), s_base+0(FP), s_len+8(FP), or s_cap+16(FP)
popcnt_amd64.s:89: [amd64] popcntXorSliceAsm: invalid offset s+8(FP); expected s+0(FP), s_base+0(FP), s_len+8(FP), or s_cap+16(FP)
exit status 1
```

**Comment by willf** [comment]
Are these easy to fix, Daniel?

—
Will

**Comment by lemire** [comment]
@nicolaasuni  

Assuming we fixed these reported issues, would you agree to keep the assembly?

(@willf  Looks like something we can fix "quickly".)

**Comment by nicolaasuni** [comment]
if fixed at least they will not break the automatic testing

**Comment by lemire** [comment]
Ok. So let us see what we can do about these issues.

**Comment by salviati** [comment]
In case you decide to keep the assembly version, the first warning can be fixed by replacing `$0` in `TEXT ·hasAsm(SB),4,$0` with `$0-1`.
Remaining warnings reported by go vet are due to recently introduced (probably in 1.5) naming conventions for accessing variables in assembly code. Replacing `s+8(FP)` with `s_len+8(FP)` should silence these warnings. `s` and `s_len` are mainly for documentation purposes.

On a related note, the upcoming assembler in go 1.6 supports `POPCNT` instructions, which can replace the `BYTE` sequences used as a work around.

**Comment by lemire** [comment]
@salviati  Thanks.

@nicolaasuni 

If you undo your commit https://github.com/cognitivelogic/bitset/commit/b7d70ac9ef3b0d9024875a6a80322b58981e4f11 and  merge in this PR https://github.com/willf/bitset/pull/37 ... then I think you will be happy (no more warnings with ```go vet```) and for people who care, they will get a ~30% performance boost for counting bits.

I think that @willf will still want to correct the naming issue... but your PR would then be uncontroversial as far as I am concerned.

**Comment by willf** [comment]
Thanks for all the work on this. I will try to get everything working together in the morning.

**Comment by nicolaasuni** [comment]
OK, I have:
- reverted the commit that removed the ASM files;
- fixed the vet errors in the popcnt_amd64.s file;
- renamed popcnt_asm.go to popcnt_amd64.s to match the correspondent ASM file;
- simplified the code.

**Comment by lemire** [comment]
Looks good.

**Comment by willf** [comment]
Ok, merged into develop and master branches. badges not quite working yet.

**Comment by salviati** [comment]
@nicolaasuni

> renamed popcnt_asm.go to popcnt_amd64.s to match the correspondent ASM file.

I would recommend using `popcnt_asm.go` with "asm" was because it doesn't actually contain anything specific to amd64. Its contents is valid for any arch, meaning it can be used without any changes if at some point you decide to add arm assembly for example. This convention is widely used in go itself (you can check `crypto/aes` package for example).

**Comment by nicolaasuni** [comment]
@salviati, I was originally thinking of using a separate go file for each asm, with different function names, so we can easily identify and test each function. However, I then realized that we can't build two architectures at the same time, so your suggestion is valid. In any case we have just to modify the "+build" settings of the popcnt_asm.go and popcnt_generic.go files as we add new implementations.

I'll send a new PR soon.

**Pull request merged**
