### PR TITLE
Add Reset function to reuse existing BitSet

### PR DESCRIPTION
**Pull request by cw9**
I have a use case where I need to decompress the bit mask on a hot path, would really like to reset the underlying words in the BitSet rather than calling From and create a new BitSet every time. 

If there is a better way to reuse the BitSet, please let me know.

### CODE REVIEW

**Comment by lemire** [comment]
Can you elaborate on what is meant by reset here?

**Comment by cw9** [comment]
Sure, I need to read the bits in a lot of uint64 slice, but I want to only create one BitSet and keep reusing the same BitSet to decode every uint64 slice rather than creating a BitSet per uint64 slice using the From() constructor. 

I could not find any API to easily reuse the BitSet now, so I created this Reset() function to accommodate that.

**Comment by lemire** [comment]
That's reasonable but I don't understand why you need to modify the library when you can just roll your own functions...

**Comment by cw9** [comment]
Yeah unfortunately I have to modify the library, the main issue with the From() is that it does a heap allocation to create a new *BitSet, adding the Reset() function in the library is the only way I can modify the underlying uint64 slice without a new heap allocation.

I could live with updating b.set word by word (although this is less ideal than just swapping the b.set), but I could not find an API that allows me to do that?

**Comment by cw9** [comment]
Found another way to work around this, this pr is no longer needed.

**Pull request closed without merging**
