### PR TITLE
Added methods for set indices

### PR DESCRIPTION
**Pull request by SamuelYvon**
Hi,

I had to use your library for a little project of mine. Since I needed an easy way to list indices of the bits that were set, I implemented it and I figured you might want it; feel free to reject or ask for changes.

### CODE REVIEW

**Comment by SamuelYvon** [comment]
After a bit of thinking, the `GenIndices` method is a bit useless, as the client cannot abort it and must consume it all (not really useful). I will append fix...

**Comment by willf** [comment]
Thanks, @SamuelYvon ! I'll give it a look

**Comment by lemire** [comment]
@willf Can you remove or fix the willf.bitset azure tests? I switched the repo to GitHub actions (it works!) and I removed travis (it was busted). I think you remove travis for good.

(I have write access to the repo., but I don't have access to the settings.)

Before you review... I am preparing a PR that I will propose on top of this PR. Just hang on a few minutes.

**Comment by willf** [comment]
Travis os gone.

**Comment by lemire** [comment]
@SamuelYvon I added Benchmarks as a PR to your PR. Please see https://github.com/SamuelYvon/bitset/pull/1

You can run the benchmark with

```
go test -test.bench BenchmarkLemireIterate
```

My results are....

```
$ go test -test.bench BenchmarkLemireIterate
BenchmarkLemireIterateManyb-8                280           4372607 ns/op
BenchmarkLemireIterateIndicesb-8             100          10987048 ns/op
BenchmarkLemireIterateChannelb-8               4         303968773 ns/op
```

Let us sum it up. 

## Indices

You propose the introduction of an`Indices` function. This new function that you propose can be computed already as ....

```
indices := make([]uint, bitSet.Count())
bitSet.NextSetMany(0, indices)
```

In fact, you could implement it already as...

```Go
func (b *BitSet) Indices() []uint {
	indices := make([]uint, b.Count())
	b.NextSetMany(0, indices)
	return indices;
}
```

I have not benchmarked it, but I bet it would be faster than the proposed implementation.

Your approach creates a new slices each time the function is called, whereas `NextSetMany` allows you to reuse the slice, thus reducing memory allocation. I think we really want to avoid unnecessary memory allocations.


Furthermore, `NextSetMany` allows you start at any point in the bitmap whereas  `Indices` always grab everything. 

So `NextSetMany` is strictly more general and versatile than `Indices` and probably more performant in almost all cases. 

The `NextSetMany` can also consume the data in blocks efficiently... 

```Go
    buffer := make([]uint, 256) // this should be reused
    j := uint(0)
    j, buffer = bitmap.NextSetMany(j, buffer)
    for ; len(buffer) > 0; j, buffer = bitmap.NextSetMany(j,buffer) {
     for k := range buffer {
      do something with buffer[k]
     }
     j += 1
    }
```

So while I admit that `bitmap.NextSetMany` is not the prettiest construction, I am concerned here about extending the API's reach with no good motivation. Doing the following ...
```
	indices := make([]uint, b.Count())
	b.NextSetMany(0, indices)
```
... is almost always better for the user. For one thing, you know, before you can any function, how much memory you are going to allocate. 

## GenIndices

You propose a channel-based iteration approach with the `GenIndices`. It allows you to iterate over the data as...

```Go
		preempt := make(chan struct{})
		defer close(preempt)
		for idx := range bitmap.GenIndices(preempt) {
			sum += idx
		}

```


The channel-based approach is 70 times slower than NextSetMany in my benchmark (see instruction above).

You offer it without motivation. I guess you are concerned with thread safety?

It would be interesting to have a motivation and maybe a benchmark that puts this new function under a good light. When is it fast and efficient?

**Comment by lemire** [comment]
@willf Do you know what the weird azure thing is? (There is a blue rocket of some kind in the PR page.)

**Comment by willf** [comment]
It can't find the `$GOROOT`.

**Comment by willf** [comment]
I'll try to get this working on a more recent Go version?

**Comment by lemire** [comment]
> I'll try to get this working on a more recent Go version?


Please do.

**Comment by SamuelYvon** [comment]
@lemire 
I was unaware of the existence of `NextSetMany()`; I think you demonstrated that this removes the need for `Indices()` as it is indeed more general. 

For `GenIndices`, the idea is indeed to distribute over go-routines (the exact application is for a combinatorial algorithm); but it might be more worthwhile (with `NextSetMany` in mind) to get everything, slice it up and then distribute the tasks. This does not fix the case where a worker finishes his workload before and end up doing nothing while the others are still working on their slice, where as with a channel the workload is balanced. 

All in all, I think `NextSetMany()` can be used to solve all the issues I had; unless you might want to salvage `GenIndices` (maybe buffering the channel and using `NextSetMany` to fill would improve performance), I suggest this PR be closed.

**Comment by lemire** [comment]
@SamuelYvon 

I don't blame you for not finding the fast approach. It is not *in your face*. 

> This does not fix the case where a worker finishes his workload before and end up doing nothing while the others are still working on their slice, where as with a channel the workload is balanced.


Yes, of course.

>  I suggest this PR be closed.

I'll close.

@willf  is the boss and he can reopen if needed.

**Pull request closed without merging**
