### PR TITLE
add support customize binaryOrder & base64.StdEncoding

### PR DESCRIPTION
**Pull request by cuixin**
Hi, these pull request code is safe for before user.

Because there are so many JSON libraries using base64 standard encoding, and also little endian.
If the code is not merged to the master branch, please let me know, thanks so much.

### CODE REVIEW

**Comment by lemire** [comment]
It does look fine.

**Comment by maciej** [comment]
@willf is there any chance to see this merged? I'm interested in getting the ability to change byte order – be it like proposed in this PR or in any other work. I'm willing to write another PR if it has a chance of getting merged.

**Comment by willf** [comment]
Yes, let me review it today. Ping me if you don't hear from me.

**Comment by willf** [comment]
@maciej Thanks for writing in, and sorry it took so long.

**Pull request merged**
