### PR TITLE
Fix All it should return false when bitset is empty

### PR DESCRIPTION
**Pull request by grudzinski**

### CODE REVIEW

**Comment by lemire** [comment]
This seems somewhat subjective. If the universe of possible values is empty, then I think the All method is ill-defined... it is effectively 0 divided by 0. So you can argue for true and false depending on your chosen point of view.

**Comment by grudzinski** [comment]
According to documentation: "All returns true if all bits are set, false otherwise", in empty bitset no bits, no set bits, so it cannot return true.

**Comment by lemire** [comment]
@grudzinski 

The C++ language has a bitset template. It defines ``all`` to be ``count() == size()``. (The C++ bitset API is similar to the willf/bitset API, see http://en.cppreference.com/w/cpp/utility/bitset/all_any_none )

To be clearer, the following C++11 code will print "1", meaning "true":

```C++
#include <bitset>
#include <iostream>
using namespace std;

int main() {
  bitset<0> B;
  cout << B.all() << endl; // C++11
}
```

So, by my interpretation, the current willf/bitset implementation is consistent with the C++11 standard, and you are proposing to make it inconsistent with it. Of course, @willf  does not have to abide by the C++11 standard, but I think one should be deliberate about such things.

Consider the following statements :

- My bag is empty.
- All balls in my bag are blue.

I submit to you that the first statement implies the second one.

**Comment by willf** [comment]
Hmm, it seems like a programmer's error to rely on an empty set returning `true` *or* `false`; I will probably update the documentation to reflect what happens when the set is empty.

**Pull request closed without merging**
